- hosts: all
  tasks:
    - name: key for apt repos
      apt_key: url=https://pkg.jenkins.io/debian/jenkins-ci.org.key
    - name: jenkins repos
      apt_repository: repo='deb http://pkg.jenkins.io/debian-stable binary/' filename=jenkins
    - name: install jenkins
      apt: name=jenkins update_cache=yes
