- name: update simple pour debian
  hosts: 127.0.0.1
  connection: local
  become: true
  tasks:
    - apt: update_cache=yes cache_valid_time=3600 upgrade=yes
      when: ansible_os_family == 'Debian'
